# PROGRAMA PARA REGISTRAR VENDA
# USUÁRIO INFORMAR NOME DO PRODUTO, PREÇO E QUANTIDADE E ADICIONAR A FATURA
# EM SEGUIDA PERGUNTAR SE O USUÁRIO QUER MAIS ALGUM PRODUTO
# SE FOR 'S' REPETE A OPERAÇÃO
# SE FOR 'N' ECERRAR OPERAÇÃO
# DEVE SER APRESENTADO O TOTAL DA FATURA
# COMPRA UMA UNID DE CADA PRODUTO POR VEZ
#######################################################################################################################



